---
- hosts: all
  become: true
  tasks:
    - name: shutdown all instances except ubuntu
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] != "Debian"
